routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomerController;


Route::get('/', function () {
    return view('auth/login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::group(['middleware' => ['auth']], function() {
// BEGIN::customer
Route::resource('/customers', CustomerController::class);
// BEGIN::customer
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;
    protected $table = 'customers';
    protected $fillable = [
        'name', 'email','active'
    ];


    public function getActiveAttribute($value)
    {
        if ($value == 1) {
            return  "Active";
        }else{
            return "Inactive";
        }
    
    }

    public function getNameAttribute($value)
    {
        return ucwords($value);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use DB;
use DataTables;
use App\Models\Customer;
use Illuminate\Http\Request;
use App\Http\Requests\CustomerRequest;
use App\Http\Controllers\Controller;

class CustomerController extends Controller
{
    public function index()
    {
        $customers = Customer::all();
        return view('customers.index',compact('customers'));
    }



    public function create()
    {
        return view('customers.create');
    }



    public function store(CustomerRequest $request)
    {
        $validated    = $request->validated();
        $customer         = Customer::create($request->all());
        return response()->json(['success'=>$request['name']. ' create successfully.']);
    }


    public function show($id)
    {
        $customers = Customer::findorFail($id);
        return view('customers.show',compact('customers'));
    }


    
    public function edit($id)
    {
        $customer  = Customer::findorFail($id);
        return view('customers.edit',compact('customer'));
    }
    

    
    public function update(CustomerRequest $request, Customer $customer)
    {

        $validated  = $request->validated();
        $customer->update($request->all());

        if(!(isset($input['active']))){
            $input['active'] = 0;
        }
    
        return response()->json(['success'=>$request['name']. ' updated successfully.']);
    }



    public function destroy(Customer $customer)
    {
          $customer->delete();
          return redirect()->route('customers.index')
                        ->with(['success'=>$customer['name'].' deleted successfully']);
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app')
@section('content')
@include( '../sweet_script')

            <div id="content">
                <div class="container-fluid">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <a href="{{ route('customers.index') }}" class="btn btn-primary" style="float: right;"><i class="fa fa-chevron-left" aria-hidden="true"></i></a>
                            <h6 class="m-0 font-weight-bold text-primary">Add Customer</h6>
                        </div>
                        <div class="card-body">
                            {!! Form::open(array('id'=>'form','enctype'=>'multipart/form-data')) !!}
                            {{  Form::hidden('action', "store" ) }}
                            <div class="row">
                                <div class="col-md-6">
                                 <div class="form-group">
                                    {!! Html::decode(Form::label('name','Name <span class="text-danger">*</span>')) !!}
                                    {{ Form::text('name', null, array('placeholder' => 'Enter name','class' => 'form-control','autofocus' => '', 'required'=>''   )) }}
                                    @if ($errors->has('name'))  
                                        {!! "<span class='span_danger'>". $errors->first('name')."</span>"!!} 
                                    @endif
                                 </div>
                                </div>
                                <div class="col-md-6">
                                 <div class="form-group">
                                    {!! Html::decode(Form::label('name','Email <span class="text-danger">*</span>')) !!}
                                    {{ Form::text('email', null, array('placeholder' => 'Enter email','class' => 'form-control','autofocus' => '' , 'required'=>''  )) }}
                                     @if ($errors->has('email'))  
                                        {!! "<span class='span_danger'>". $errors->first('email')."</span>"!!} 
                                     @endif
                                 </div>
                                </div>
                            </div>
                            <br>
                            <button type="submit" class="btn btn-primary add_customer">Submit</button>
                            <button type="reset" class="btn btn-danger">Cancel</button>
                             {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>

        <!--- ajax ---->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

        <script>
        $(document).ready(function () {  

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('#form').submit(function(e) {
                e.preventDefault();
                var formData = new FormData(this);
                $.ajax({
                    type: 'POST',
                    url: "{{ route('customers.store') }}",
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: (data) => {
                        if(data.success){
                            this.reset();
                            toastr.success(data.success);
                        }
                    },
                    error: function(data) {
                        var txt         = '';
                        // console.log(data.responseJSON.errors)
                        for (var key in data.responseJSON.errors) {
                            txt += data.responseJSON.errors[key];
                            txt +='<br> ';
                        }
                        toastr.error(txt);
                    }
                });
            });
        });
    </script>
    

@endsection

resources/views/customers/edit.blade.php
@extends('layouts.app')
@section('content')
@include( '../sweet_script')

            <div id="content">
                <div class="container-fluid">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <a href="{{ route('customers.index') }}" class="btn btn-primary" style="float: right;"><i class="fa fa-chevron-left" aria-hidden="true"></i></a>
                            <h6 class="m-0 font-weight-bold text-primary">update Customer</h6>
                        </div>
                        <div class="card-body">
                            {!! Form::model($customer, ['method' => 'PATCH','id'=>'form','enctype'=>'multipart/form-data']) !!}
                            {{  Form::hidden('action', "update" ) }}
                            <div class="row">
                                <div class="col-md-6">
                                 <div class="form-group">
                                    {!! Html::decode(Form::label('name','Name <span class="text-danger">*</span>')) !!}
                                    {{ Form::text('name', null, array('placeholder' => 'Enter name','class' => 'form-control','autofocus' => '', 'required'=>''  )) }}
                                     @if ($errors->has('name'))  
                                        {!! "<span class='span_danger'>". $errors->first('name')."</span>"!!} 
                                    @endif
                                 </div>
                                </div>
                                <div class="col-md-6">
                                 <div class="form-group">
                                    {!! Html::decode(Form::label('email','Email <span class="text-danger">*</span>')) !!}
                                    {{ Form::text('email', null, array('placeholder' => 'Enter email','class' => 'form-control','autofocus' => '', 'required'=>''  )) }}
                                    @if ($errors->has('fname'))  
                                        {!! "<span class='span_danger'>". $errors->first('fname')."</span>"!!} 
                                    @endif
                                 </div>
                                </div>
                            </div>
                             <div class="form-group">
                                <?php
                                $actv = 0;
                                if ($customer->active == "Active") {
                                $actv = 1;
                                }          
                                ?>
                                {!! Html::decode(Form::label('active','Status <span class="text-danger">*</span>')) !!}
                                {!! Form::select('active', ["1" => "Active" ,"0" =>"Inactive"] ,$actv, array('class' => 'form-control')) !!}
                                 </div>
                            <br>
                            <button type="submit" class="btn btn-primary add_customer">Submit</button>
                            <button type="reset" class="btn btn-danger">Cancel</button>
                            {!! Form::close() !!}
                        </div>
                    </div>

                </div>
            </div>


            <!---- ajax ---->


            
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    
    <script>
        $(document).ready(function () {  
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('#form').submit(function(e) {
                e.preventDefault();
                var formData = new FormData(this);
                
                $.ajax({
                    type: 'POST',
                    url: "{{ route('customers.update',$customer->id) }}",
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: (data) => {
                        if(data.success){
                            // this.reset();
                            toastr.success(data.success);
                        }else{
                            if (typeof (data.error) !== 'undefined') {
                                toastr.error(data.error);
                            }
                        }
                    },
                    error: function(data) {
                        var txt = '';
                        for (var key in data.responseJSON.errors) {
                            txt += data.responseJSON.errors[key];
                            txt +='<br>';
                        }
                        toastr.error(txt);
                    }
                });
            });
        });
    </script>

@endsection

resources/views/customers/index.blade.php
@extends('layouts.app')
@section('content')
@include( '../sweet_script')
            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <a href="{{ route('customers.create') }}" class="btn btn-primary" style="float: right;"><i class="fa fa-plus" aria-hidden="true"></i></a>
                            <h6 class="m-0 font-weight-bold text-primary">Manage Customers</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="myTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Active</th>
                                        <th style="width:20%;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($customers as $customer)
                                        <tr>
                                            <td>{{((isset($customer->name))   ?  $customer->id : "")}}</td>
                                            <td>{{((isset($customer->name))   ?  $customer->name : "")}}</td>
                                            <td>{{((isset($customer->email))  ?  $customer->email : "")}}</td>
                                            <td>{{((isset($customer->active)) ?  $customer->active : "")}}</td>
                                            <td>
                                                <form action="{{ route('customers.destroy',$customer->id) }}" method="POST">
                                   
                                                    <a class="btn btn-primary btn-sm" href="{{ route('customers.show',$customer->id) }}">
                                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                                    </a>
                                    
                                                    <a class="btn btn-primary btn-sm" href="{{ route('customers.edit',$customer->id) }}"><i class="fa fa-edit" aria-hidden="true"></i></a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm btn-flat show_confirm" data-toggle="tooltip" title='Delete'><i class="fa fa-trash-alt" aria-hidden="true"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </div>
               
               <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
               <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
               <script type="text/javascript">
                 $('.show_confirm').click(function(event) {
                      var form =  $(this).closest("form");
                      var name = $(this).data("name");
                      event.preventDefault();
                      swal({
                          title: `Are you sure delete this customer`,
                          icon: "warning",
                          buttons: true,
                          dangerMode: true,
                      })
                      .then((willDelete) => {
                        if (willDelete) {
                          form.submit();
                        }
                      });
                  });
              
            </script>

@endsection

resources/views/customers/show.blade.php
@extends('layouts.app')
@section('content')               
    @include( '../sweet_script')

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <a href="{{ route('customers.index') }}" class="btn btn-primary" style="float: right;"><i class="fa fa-chevron-left" aria-hidden="true"></i></a>
                            <h6 class="m-0 font-weight-bold text-primary">View Customer</h6>
                        </div>
                        <div class="card-body">

                             <strong># :</strong>
                             <label style="font-size: 15px;" class="element">{{ $customers->id }}</label>
                             <br>
                             <hr>

                             <strong>Name :</strong>
                             <label style="font-size: 15px;" class="element">{{ $customers->name }}</label>
                             <br>
                             <hr>
                             
                             <strong>Email :</strong>
                             <label style="font-size: 15px;" class="element">{{ $customers->email }}</label>
                             <br>
                             <hr>
                             
                             <strong>Status :</strong>
                             <label style="font-size: 15px;" class="element">{{ $customers->active }}</label>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Main Content -->

@endsection

resources/views/dashboard.blade.php
@extends('layouts.app')
@section('content')
            <div id="content">
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
                    </div>

                    <!-- Content Row -->
                    <div class="row">

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-primary shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                Earnings (Monthly)</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-success shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                                Earnings (Annual)</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-info shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                                            </div>
                                            <div class="row no-gutters align-items-center">
                                                <div class="col-auto">
                                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                                                </div>
                                                <div class="col">
                                                    <div class="progress progress-sm mr-2">
                                                        <div class="progress-bar bg-info" role="progressbar"
                                                            style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                                            aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Pending Requests Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-warning shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                                Pending Requests</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
           @endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

@include('layouts.head_script')

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

       @include('layouts.sidebar')

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
 
            @include('layouts.navbar')
            @yield('content') 
            @include('layouts.footer')
        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


@include('layouts.footer_script')

</body>

</html>

resources/views/layouts/footer.blade.php
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

resources/views/layouts/footer_script.blade.php
    <!-- Bootstrap core JavaScript-->
    
    <script src="{{asset ('vendor/jquery/jquery.min.js')}}"></script>
    
    <script src="{{asset ('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

    <script src="{{asset('vendor/jquery-easing/jquery.easing.min.js')}}"></script>

    <script src="{{asset('js/sb-admin-2.min.js')}}"></script>
    
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
    
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
    
    <script src="{{ asset('js/demo/datatables-demo.js')}}"></script>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/head_script.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hunting - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{{asset('vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{asset ('css/sb-admin-2.min.css')}}" rel="stylesheet">

      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
</head>

resources/views/layouts/sidebar.blade.php
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('dashboard') }}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">WELCOME</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{{ route('dashboard') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-users fa-cog"></i>
                    <span>Customers</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a style="text-decoration: none; color: black;" href="{{route('customers.index')}}" class="collapse-header">Manage customers</a>
                    </div>
                </div>
            </li>
        </ul>
        <!-- End of Sidebar -->